### ISSUE TITLE
py-utils require Python 3.7 or higher

### ISSUE THREAD

**Issue by knekrasov** [Seagate/cortx-utils#169]
Just noticed that nowadays py-utils fails to build locally with Python 3.6.8 with the error as follows:

```
$ python ./setup.py develop
<...>
Installed /home/720599/projects/cortx-utils/py-utils
Processing dependencies for cortx-py-utils==1.0.0
Searching for numpy>=1.11
Reading https://pypi.org/simple/numpy/
Downloading https://files.pythonhosted.org/packages/77/17/b7ad8757cca32031cd6440b1e79403f9b5e7b0b68d57df40cb72eba311ba/numpy-1.20.0rc2.zip#sha256=793383d52f79c785ad2e7cf24b064f8ff5041ee0e44cef34368918c1b89e9d58
Best match: numpy 1.20.0rc2
Processing numpy-1.20.0rc2.zip
Writing /tmp/easy_install-vqc2godw/numpy-1.20.0rc2/setup.cfg
Running numpy-1.20.0rc2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-vqc2godw/numpy-1.20.0rc2/egg-dist-tmp-a9bhgtcy
Traceback (most recent call last):
  File "/home/720599/projects/hare/.py3venv/lib64/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/720599/projects/hare/.py3venv/lib64/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/720599/projects/hare/.py3venv/lib64/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/720599/projects/hare/.py3venv/lib64/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-vqc2godw/numpy-1.20.0rc2/setup.py", line 30, in <module>

RuntimeError: Python version >= 3.7 required.
```

It turns out that `numpy` is a transitive dependency required by `matplotlib`:
```
  - matplotlib [required: ==3.1.3, installed: 3.1.3]
    - cycler [required: >=0.10, installed: ?]
    - kiwisolver [required: >=1.0.1, installed: ?]
    - numpy [required: >=1.11, installed: ?]
    - pyparsing [required: >=2.0.1,!=2.1.6,!=2.1.2,!=2.0.4, installed: 3.0.0b2]
    - python-dateutil [required: >=2.1, installed: 2.8.1]
      - six [required: >=1.5, installed: 1.15.0]
```

# Why it is a problem
1. Other components (like Hare) are stick to Python 3.6. If we change the python version in Cortx stack, that decision must be applied to all components and definitely should not happen silently.
2. It seems like other parts of `py-utils` are not adapted to this newer Python version. For instance,  https://github.com/Seagate/cortx-utils/blob/d78a85c34dd6e79a847d0ae20d893220590b378d/py-utils/utils-post-install uses `pip3.6` (not `pip` or `pip3` or `pip3.7`)

**Comment by sachinpunadikar** [comment]
Fixed this via PR https://github.com/Seagate/cortx-utils/pull/186
Closing this issue
