### ISSUE TITLE
py-utils doesn't ship all its dependencies with RPM

### ISSUE THREAD

**Issue by knekrasov** [Seagate/cortx-utils#183]
JIRA: https://jts.seagate.com/browse/EOS-17269

After installing py-utils RPM I'm still not able to import types from `cortx.utils` due to missing dependencies. In my case the error is as follows:
```
======================================================================
ERROR: main (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: main
Traceback (most recent call last):
  File "/usr/lib64/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/720599/projects/hare/provisioning/miniprov/hare_mp/main.py", line 35, in <module>
    from cortx.utils.product_features import unsupported_features
  File "/usr/lib/python3.6/site-packages/cortx/utils/product_features/unsupported_features.py", line 19, in <module>
    from cortx.utils.data.access import Query
  File "/usr/lib/python3.6/site-packages/cortx/utils/data/access/__init__.py", line 18, in <module>
    from .base_model import BaseModel
  File "/usr/lib/python3.6/site-packages/cortx/utils/data/access/base_model.py", line 16, in <module>
    from schematics.models import Model
ModuleNotFoundError: No module named 'schematics'
```

So my unit test failed because the following import chain was broken: `cortx.utils.product_features.unsupported_features` -> `cortx.utils.data.access.Query` -> (BaseModel class) -> `schematics.models.Model`.

Second example - `elasticsearch_dsl`: 
```
======================================================================
ERROR: main (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: main
Traceback (most recent call last):
  File "/usr/lib64/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/720599/projects/hare/provisioning/miniprov/hare_mp/main.py", line 35, in <module>
    from cortx.utils.product_features import unsupported_features
  File "/usr/lib/python3.6/site-packages/cortx/utils/product_features/unsupported_features.py", line 21, in <module>
    from cortx.utils.data.db.db_provider import DataBaseProvider, GeneralConfig
  File "/usr/lib/python3.6/site-packages/cortx/utils/data/db/__init__.py", line 19, in <module>
    from cortx.utils.data.db.elasticsearch_db import ElasticSearchDB
  File "/usr/lib/python3.6/site-packages/cortx/utils/data/db/elasticsearch_db/__init__.py", line 18, in <module>
    from cortx.utils.data.db.elasticsearch_db.storage import ElasticSearchDB
  File "/usr/lib/python3.6/site-packages/cortx/utils/data/db/elasticsearch_db/storage.py", line 25, in <module>
    from elasticsearch_dsl import Q, Search, UpdateByQuery
ModuleNotFoundError: No module named 'elasticsearch_dsl'
```

## Problem
Although cortx-py-utils RPM is installed, `schematics` Python package is not available it is obviously a dependency of py-utils.

## py-utils version

```
$ rpm -qa 'cortx-py*'
cortx-py-utils-1.0.0-92_8b3c613.noarch
```

**Comment by sachinpunadikar** [comment]
Latest rpm, before installation checks for all required python packages.
If any package is missing, it will throw a message with required package details, and stops the installation.
If all required packages are available it will happily install cortx-py-utils rpm.
Marking this issue as resolved.
