### ISSUE TITLE
Installing py-utils causes error

### ISSUE THREAD

**Issue by hessio** [Seagate/cortx-utils#812]
### Problem

When running: 

` sudo pip3 install -r https://raw.githubusercontent.com/Seagate/cortx-utils/main/py-utils/python_requirements.txt`

Causes error:

`    copying src/nacl/bindings/crypto_scalarmult.py -> build/lib.linux-x86_64-3.6/nacl/bindings
    copying src/nacl/py.typed -> build/lib.linux-x86_64-3.6/nacl
    running build_clib
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0d6c7teu/pynacl/setup.py", line 232, in <module>
        "Programming Language :: Python :: 3.10",
      File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib64/python3.6/distutils/command/install.py", line 556, in run
        self.run_command('build')
      File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib64/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-0d6c7teu/pynacl/setup.py", line 141, in run
        raise Exception("ERROR: The 'make' utility is missing from PATH")
    Exception: ERROR: The 'make' utility is missing from PATH

    ----------------------------------------
Command "/usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-0d6c7teu/pynacl/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-5nom4xfh-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-0d6c7teu/pynacl/
`

### Expected behavior

All packages should install without error

### How to reproduce

trying to install requirements on Rocky Linux 8.4

` sudo pip3 install -r https://raw.githubusercontent.com/Seagate/cortx-utils/main/py-utils/python_requirements.txt`

### Deployment information

Rocky Linux 8.4

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-31236. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by hessio** [comment]
solution provided

**Comment by cortx-admin** [comment]
> Chetan Deshmukh commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Chetan Deshmukh commented in Jira Server:

.
